### ISSUE TITLE
Error #1

### ISSUE THREAD

**Issue by xxxWILL-INFxxx** [InfinityGamers/TradeUI#1]
Exception: "Unable to open database: unable to open database file" (EXCEPTION) in "TradeUI/src/TradeUI/TradeUI" at line 53

**Comment by xBeastMode** [comment]
You need to add read/write permissions to the plugin. Search up how give read and write permissions to folder depending on your OS.

**Comment by ASANITA** [comment]
I don't understand can you explain?

**Comment by ASANITA** [comment]
I give it the permission but it doesn't work
