### ISSUE TITLE
Removing an item from /myoffers loses the enchanted properties

### ISSUE THREAD

**Issue by isoz** [InfinityGamers/TradeUI#4]
As the title states when you remove an item from myoffers you will lose the enchantments, in my case it was a diamond pickaxe with efficiency 5.

Edit:
Also I assume this happens when someone buys it as well, haven't tried.

**Comment by xBeastMode** [comment]
You can help me solve the last issue first by responding to what I asked, telling me your PocketMine and Minecraft version. That is usually how I solve issues as I can't read other's minds. ;)

**Comment by xBeastMode** [comment]
Please add this to your server so I can review the last issue.

**Comment by isoz** [comment]
Done. Added to SkyBlock.
