### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by iZeaoGamer** [InfinityGamers/TradeUI#8]
Hi, so I was trying to install this plugin, and this error came up when trying to enable:
Enabling TradeUI v1.3
21.08 16:03:41 [Server] Server thread/CRITICAL Exception: "Unable to open database: unable to open database file" (EXCEPTION) in "TradeUI-master/src/TradeUI/TradeUI" at line 55
21.08 16:03:41 [Server] Server thread/DEBUG #0 TradeUI-master/src/TradeUI/TradeUI(55): SQLite3->__construct(string /plugin_data/TradeUI/auctionHouse.sqlite)
21.08 16:03:41 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/PluginBase(102): TradeUI\TradeUI->onEnable()
21.08 16:03:41 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginManager(611): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
21.08 16:03:41 [Server] Server thread/DEBUG #3 src/pocketmine/Server(1931): pocketmine\plugin\PluginManager->enablePlugin(TradeUI\TradeUI object)
21.08 16:03:41 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1917): pocketmine\Server->enablePlugin(TradeUI\TradeUI object)
21.08 16:03:41 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1711): pocketmine\Server->enablePlugins(integer 1)
21.08 16:03:41 [Server] Server thread/DEBUG #6 src/pocketmine/PocketMine(237): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
21.08 16:03:41 [Server] Server thread/DEBUG #7 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)
21.08 16:03:41 [Server] Server thread/INFO Disabling TradeUI v1.3
I hope you can fix this, thanks.

**Comment by xBeastMode** [comment]
Read the solution in #1
